# Generated by Django 3.0.4 on 2020-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('picture_URL', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('repo', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
